services:
  backend:
    build:
      context: . 
      dockerfile: Dockerfile  # Use the backend Dockerfile
    container_name: backend101
    restart: always
    working_dir: /app/backend
    env_file:
      - .env
    ports:
      - "5001:5001"  # Expose backend on port 5001
    volumes:
      - .:/app/backend
      - node_modules:/app/backend/node_modules
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend  # Set context to the frontend directory
      dockerfile: Dockerfile  # Use the frontend Dockerfile inside the frontend directory
    container_name: frontend101
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"  # Expose frontend on port 80
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    restart: always
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"  # Expose Nginx server on port 80
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  node_modules: {}
